CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE TABLE empresas (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(200) NOT NULL,
        "RFC" character varying(13) NOT NULL,
        "Direccion" text,
        "ConfiguracionJson" text,
        "Activa" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        CONSTRAINT "PK_empresas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE TABLE usuarios (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmpresaId" integer NOT NULL,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" text NOT NULL,
        "NombreCompleto" character varying(200) NOT NULL,
        "Rol" integer NOT NULL,
        "Activo" boolean NOT NULL,
        "UltimoAcceso" timestamp with time zone,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        CONSTRAINT "PK_usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_usuarios_empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES empresas ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE TABLE areas (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmpresaId" integer NOT NULL,
        "Nombre" character varying(150) NOT NULL,
        "SupervisorId" integer,
        "Descripcion" text,
        "Activa" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        CONSTRAINT "PK_areas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_areas_empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES empresas ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_areas_usuarios_SupervisorId" FOREIGN KEY ("SupervisorId") REFERENCES usuarios ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE TABLE empleados (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmpresaId" integer NOT NULL,
        "AreaId" integer NOT NULL,
        "UsuarioId" integer,
        "NumeroEmpleado" character varying(50) NOT NULL,
        "Nombre" character varying(150) NOT NULL,
        "Apellidos" character varying(150) NOT NULL,
        "FechaIngreso" timestamp with time zone NOT NULL,
        "SalarioDiario" numeric(10,2) NOT NULL,
        "TurnoId" integer,
        "IdBiometrico" text,
        "Activo" boolean NOT NULL,
        "Puesto" text,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        CONSTRAINT "PK_empleados" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_empleados_areas_AreaId" FOREIGN KEY ("AreaId") REFERENCES areas ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_empleados_empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES empresas ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_empleados_usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES usuarios ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE INDEX "IX_areas_EmpresaId" ON areas ("EmpresaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE INDEX "IX_areas_SupervisorId" ON areas ("SupervisorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE INDEX "IX_empleados_AreaId" ON empleados ("AreaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_empleados_EmpresaId_NumeroEmpleado" ON empleados ("EmpresaId", "NumeroEmpleado");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE INDEX "IX_empleados_UsuarioId" ON empleados ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_empresas_RFC" ON empresas ("RFC");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_usuarios_EmpresaId_Email" ON usuarios ("EmpresaId", "Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213144304_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260213144304_InitialCreate', '9.0.0');
    END IF;
END $EF$;
COMMIT;

